untitled1/urls.py
import os

from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from BuctLib import views
from django.views.generic.base import RedirectView


urlpatterns = (
    path('admin/', admin.site.urls),
    path('loginout/', views.loginout),
    path(r'', views.loginpage),
    path(r'debug/', views.hello),
    path(r'pwdmdf/', views.pwdmdf),
    path(r'admin_pwdmdf/', views.admin_pwdmdf),
    path(r'login/', views.logincheck),
    path(r'register/', views.register),
    path(r'readerindex/', views.readerindex),
    path(r'adminindex/', views.adminindex),
    path(r'registercheck/', views.registerCheck),
    path(r'book_operation/', views.book_admin),
    path(r'add_book/', views.add_book),
    path(r'check_borrow/', views.check_borrow),
    path(r'check_borrow_op/', views.check_borrow_op),
    path(r'admin_showillegal/', views.admin_showillegal),
    path(r'admin_deletebr/', views.admin_deletebr),
    path(r'remind/', views.remind_reader),
    path(r'admin_apply_check/', views.apply_check),
    path(r'apply_check_ajax/', views.apply_check_ajax),
    path(r'delete_reader/', views.delete_reader),
    path(r'delete_reader_ajax/', views.delete_reader_ajax),
    path(r'class_mdf_list/', views.class_mdf_list),
    path(r'fine_mdf_list/', views.fine_mdf_list),
    path(r'404/', views.page404),
    path(r'jump/', views.jump),
    path(r'add_user/', views.add_user),
    path(r'add_class/', views.add_class),
    path(r'add_fine/', views.add_fine),
    path(r'resetApply/', views.resetapply),
    path(r'checkpwd/', views.checkpwd),
    path(r'admin_checkpwd/', views.admin_checkpwd),
    path(r'todaycommend/', views.commend),
    path(r'admin_todaylib/', views.admin_datavisual),
    path(r'todaylib/', views.datavisual),
    path(r'getmessage/', views.getmessage),
    path(r'applyclass/', views.apllyclass),
    path(r'getborrow/', views.getborrow),
    path(r'getmesnum/', views.getmesnum),
    path(r'notreturn/', views.showbred),
    path(r'return/', views.returnbook),
    path(r'cancelNotice/', views.cancelNotice),
    path(r'admin_infmdf/', views.admin_infmdf),
    path(r'returned/', views.showreturned),
    path(r'illegal/', views.showillegal),
    path(r'sendMessage/', views.sendMessage),
    path(r'sendNotice/', views.sendNotice),
    path(r'deletebr/', views.deletebr),
    path(r'admin_class_fine_ajax/', views.admin_class_fine_ajax),
    path(r'admin_searchresult/', views.admin_searchbooks),
    url(r'class_mdf/([^/]+)/$', views.class_mdf, name='class_mdf'),
    url(r'fine_mdf/(\d+)/$', views.fine_mdf, name='fine_mdf'),
    url(r'admin_illegal_report/(\d+)/$', views.admin_illegal_report, name="admin_illegal"),
    url(r'checking/', views.checkingbooks, name='checking'),
    url(r'brrow/', views.borrow, name='borrow'),
    url(r'searchresult/', views.searchbooks, name="searchbooks"),
    url(r'delayreturn/(\d+)/$', views.delayreturn, name='delay'),
    url(r'illegalreport/(\d+)/$', views.illegal_report, name="illegal"),
    url(r'admin_allnotices', views.admin_allnotice, name='admin_allnotices'),
    url(r'admin_noticedetail/(\d+)/$', views.admin_noticedetail, name="admin_noticepage"),
    url(r'admin_bookdetail/(\d+)/$', views.admin_bookdetail, name='admin_bookdetail'),
    url(r'allnotice/', views.allnotice, name='allnotice'),
    url(r'noticedetail/(\d+)/$', views.noticedetail, name='noticepage'),
    url(r'bookdetail/(\d+)/$', views.bookdetail, name='bookdetail'),
    url(r'infomdf/', views.infmdf, name="modify information"),
    url(r'favicon.ico/', RedirectView.as_view(url=r'/static/img/icons/lib.svg')),
)

BuctLib/models.py
from django.db import models


GENDER_CHOICE = [
    ('1', '男'),
    ('2', '女'),
    ('3', '保密')
]


LibFloor = [
    ('1', '图书馆一层'),
    ('2', '图书馆二层'),
    ('3', '图书馆三层'),
    ('4', '图书馆四层'),
]

SCHOOLS = [
    ('1', '电子信息与工程学院'),
    ('2', '材料科学与工程学院'),
    ('3', '机电工程学院'),
    ('4', '化学工程学院'),
    ('5', '经济管理学院'),
    ('6', '天体物理学院'),
    ('7', '数理学院'),
    ('8', '文法学院'),
    ('9', '生命科学与技术学院'),
    ('10', '继续教育学院'),
    ('11', '马克思主义学院'),
    ('12', '国际教育学院'),
    ('13', '交通学院'),
    ('14', '中德学院'),

]

ACCOUNT_TPYE = [
    ('1', '管理员'),
    ('2', '读者'),
]

CATEGORY_CHOICE = [
        ('思政类', '思政类'),
        ('哲学类', '哲学类'),
        ('社会科学类', '社会科学类'),
        ('军事类', '军事类'),
        ('经济类', '经济类'),
        ('文化科学类', '文化科学类'),
        ('语言文字类', '语言文字类'),
        ('文学类', '文学类'),
        ('艺术类', '艺术类'),
        ('体育类', '体育类'),
        ('历史地理类', '历史地理类'),
        ('自然科学总论类', '自然科学总论类'),
        ('数理化学类', '数理化学类'),
        ('天文地球科学类', '天文地球科学类'),
        ('生物科学理类', '生物科学理类'),
        ('医药类', '医药类'),
        ('农业科学类', '农业科学类'),
        ('工业技术类', '工业技术类'),
        ('交通运输类', '交通运输类'),
        ('航空航天类', '航空航天类'),
        ('环境科学类', '环境科学类'),
        ('计算机类', '计算机类'),
        ('未分类', '未分类')
    ]


class Book(models.Model):
    """
    图书类  查询图书信息
    主键： 图书编号 BookID
    属性： ISBN ISBN 书名BName  出版社Publisher
    作者 Author 图书简介 Content 馆藏数量 NumInLib 在架数量 NumNow
    分类 Category 出版时间 PubTime
    ReadTimes 阅读数
    TODO(ChouEV) 图书封面 BImage
    """
    BookID = models.AutoField(primary_key=True, db_index=True)
    BName = models.CharField(max_length=40)
    Publisher = models.CharField(max_length=40)
    Author = models.CharField(max_length=30)
    Content = models.TextField(default="无", blank=True, null=True)
    Price = models.FloatField(default=30.0)
    NumInLib = models.PositiveSmallIntegerField(default=0)
    NumNow = models.PositiveSmallIntegerField(default=0)
    Category = models.CharField(max_length=30, default="未分类", choices=CATEGORY_CHOICE)
    PubTime = models.DateField(default="1999-10-11")
    ReadTimes = models.IntegerField(default=0)

    def __str__(self):
        return self.BName

    def save(self, *args, **kwargs):
        if self.NumInLib < self.NumNow:
            raise Exception("在架数量不能超过馆藏数量")
        else:
            super(self.__class__, self).save(*args, **kwargs)


class User(models.Model):
    """
     用户类 用于登陆
     主键： 账户名 AccountID
     属性： 密码 Password 账户类别 Type
        邮箱 Email 电话 Tel
     """
    AccountID = models.CharField(max_length=40, primary_key=True, db_index=True)
    Password = models.CharField(max_length=40)
    Type = models.CharField(choices=ACCOUNT_TPYE, default="读者", max_length=10)  # 默认为普通用户
    Email = models.EmailField(unique=True)
    Tel = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.AccountID


class Manager(models.Model):
    """
    管理员类 查询管理员信息
    主键： 工号 ManagerID
    外键： 账户名 AccountID
    属性：  性别 Gender 姓名 MName
    TODO(ChouEV) 管理员照片 MImage
    """

    ManagerID = models.CharField(primary_key=True, max_length=30, db_index=True)
    AccountID = models.OneToOneField(to="User", on_delete=models.CASCADE)
    Gender = models.CharField(max_length=10, choices=GENDER_CHOICE, default="保密")
    Name = models.CharField(max_length=30, null=True)

    def __str__(self):
        return self.ManagerID


class ReaderClass(models.Model):
    """
    读者级别类
    Class为级别
    Limited为可借阅数量
    Day为借阅天数
    """
    Class = models.CharField(max_length=10, primary_key=True, db_index=True)
    Limited = models.PositiveSmallIntegerField(default=3)
    Days = models.PositiveSmallIntegerField(default=30, null=True)

    def __str__(self):
        return self.Class


class Reader(models.Model):
    """
     读者类 查阅读者信息
     主键： 学号 ReaderID
     外键： 账户名 AccountID
     属性：  性别 Gender 姓名 SName
     学院 School
     类型 Type
    TODO(ChouEV) 读者照片 MImage
     """
    ReaderID = models.CharField(primary_key=True, max_length=30, db_index=True)
    AccountID = models.OneToOneField(User, on_delete=models.CASCADE)
    Gender = models.CharField(max_length=10, choices=GENDER_CHOICE, default="保密")
    Name = models.CharField(max_length=30, null=True, blank=True)
    School = models.CharField(max_length=30, choices=SCHOOLS, default="信息技术与科学学院")
    Class = models.ForeignKey(to="ReaderClass", on_delete=models.SET_DEFAULT, default="A")
    Type = models.CharField(max_length=10, choices=[('1', '学生'), ('2', '教职工')],  default='学生')

    def __str__(self):
        return self.ReaderID


class Fine(models.Model):
    """
    处罚规则类
    LimitDay是小于该期限的处罚金额
    FineMoney是处罚金额
    """
    LimitDay = models.PositiveSmallIntegerField(unique=True, db_index=True)
    FineMoney = models.PositiveSmallIntegerField(default=0)


class ApplyClass(models.Model):
    """
        借阅记录类
        主键 默认id
        外键 class 申请的级别 ReaderID 申请的读者ID号
    """
    Class = models.ForeignKey(to="ReaderClass", on_delete=models.CASCADE)
    ReaderID = models.ForeignKey(to="Reader", on_delete=models.CASCADE)
    Message = models.TextField(default="")


class Borrow(models.Model):
    """
    借阅记录类
    主键 学号 ReaderID &&  图书编号 BookID
    外键 学号 ReaderID &&  图书编号 BookID
    借书时间 BorrowTime 还书日期 returnTime
    续借状态 isReBorrowed
    """
    ReaderID = models.ForeignKey(to="Reader", on_delete=models.CASCADE)
    BookID = models.ForeignKey(to="Book", on_delete=models.CASCADE)
    BorrowTime = models.DateField(auto_now_add=True)
    ReturnDay = models.DateField(auto_now_add=True)
    RealreturnDay = models.DateField(default='2020-01-01')
    isReBorrowed = models.BooleanField(default=False)
    isLegal = models.NullBooleanField(default=True)
    isDelete = models.BooleanField(default=False)
    isReturned = models.BooleanField(default=False)
    isAllowed = models.NullBooleanField(null=True)

    def __str__(self):
        return "学生%s借了%s书" % (self.ReaderID, self.BookID)


class BuyIn(models.Model):
    """
    进货类
    TODO(ChouEV) 记录进货厂商 进货时间 进货书籍 进货负责人（管理员）
    """
    pass


class Message(models.Model):
    """
    消息类
    """
    STATUS = [
        ('1', '已读'),
        ('2', '未读')
    ]
    Title = models.CharField(max_length=255, verbose_name='消息标题')
    ReaderID = models.ForeignKey(to="Reader", on_delete=models.CASCADE)
    Content = models.TextField()
    MTime = models.DateTimeField(auto_now_add=True)
    Status = models.CharField(max_length=20, choices=STATUS, default="未读")

    def __str__(self):
        return "消息主题：" + self.Title


class Notice(models.Model):
    """
    公告类
    """
    Title = models.CharField(max_length=40)
    NTime = models.DateTimeField(auto_now_add=True)
    Content = models.TextField()
    ReadTimes = models.IntegerField(default=0)

    def __str__(self):
        return "公告主题：" + self.Title

templates/student/library/all_notice.html
{%  extends "model/base.html" %}
{% block title %} 所有公告 {% endblock %}
<!--JS代码-->
{% block script %}

{% endblock %}
<!--css代码-->
{% block StyleSheet %}
{%  endblock %}

{% block content %}
    <div class="row">
          <div class="col-md-12">
            <!-- The time line -->
            <div class="timeline">
              {% for item in notices %}
                  <!--年加月份-->
              <div class="time-label">
                <span class="bg-red">{{ item.YM }}</span>
              </div>
              <!--每个项-->
                  {% for notice in item.notices %}
              <div>
                <i class="fas fa-bullhorn bg-blue"></i>
                <div class="timeline-item">
                  <span class="time"><i class="fas fa-clock"></i> {{ notice.NTime }}</span>
                  <h3 class="timeline-header">阅读次数： {{ notice.ReadTimes }}</h3>

                  <div class="timeline-body">
                        <h4 class="font-weight-bold">{{ notice.Title }}</h4>
                  </div>
                  <div class="timeline-footer">
                    <a class="btn btn-primary btn-sm" href="{% url 'noticepage' notice.id %}">阅读</a>

                  </div>
                </div>
              </div>
                      {% endfor %}
             {% endfor %}
              <div>
                <i class="fas fa-clock bg-gray"></i>
              </div>
            </div>
          </div>
          <!-- /.col -->
        </div>
{% endblock %}

templates/student/library/notice_detail.html
{% extends 'model/base.html' %}

{%  block title %}
    公告详情
{% endblock %}

{% block StyleSheet %}
    <style>

    </style>
{%  endblock %}
{% block script %}
    <script>
    $(function () {
        $("#fontMin").click(function () {
            $("#notice-container").css("font-size", "15px");
        })
        $("#fontMid").click(function () {
            $("#notice-container").css("font-size", "20px");
        })
        $("#fontMax").click(function () {
            $("#notice-container").css("font-size", "25px");
        })
    })
    </script>
{% endblock %}

{% block content %}
    <div class="col-lg-12 " >
            <div class="card font" >
              <div class="card-header gradient-color-her">
                <h3 class="card-title">公告详情</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="maximize"><i class="fas fa-expand" style="color: white"></i>
                  </button>
                </div>
                <!-- /.card-tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body" style="overflow-y: scroll;max-height: 100%;" >
                  <div class="row">
                    <h2 class="title m-auto font-weight-bold font-gradient" >{{ notice.Title }}</h2>
                  </div>
                  <div class="row"  style="margin-top: 10px">
                        <p class="m-auto"><a id="fontMin" href="#">[小]</a>&nbsp;&nbsp;&nbsp;<a id="fontMid" href="#">[中]</a>&nbsp;&nbsp;&nbsp;<a id="fontMax" href="#">[大]</a></p>
                  </div>
                  <div class="row" style="margin-top: 10px ; padding-bottom: 10px;border-bottom: 1px solid #d3d7d4 ;">
                      <h6 class="m-auto"><strong>发布日期：&nbsp;&nbsp;</strong>{{ notice.NTime }}
                          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                          <strong>阅读次数：&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ notice.ReadTimes }} </h6>
                  </div>
                  <div class="noticebody row" id="notice-container" style="font-size: 20px;margin-top: 20px; min-height: 340px">


                      <p class="col-lg-8 offset-lg-2" >{{ notice.Content|linebreaksbr }}</p>

                  </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>

{% endblock %}

templates/student/library/searchbooks.html
{%  extends 'model/base.html' %}
{% block title %}
图书检索
{% endblock %}
<!--样式-->
{% block StyleSheet %}
 <link rel="stylesheet" href="/static/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
    <style>
        .selection{
            cursor: pointer;
        }
    </style>
{% endblock %}
{% block script %}
{#    表格元素#}

   <script src="/static/plugins/datatables/jquery.dataTables.js"></script>
<script src="/static/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script>
     $(function () {
            $("#example1").DataTable({"language": {"url": "/static/plugins/datatables/Chinese.json"},
                "language": {"url": "/static/plugins/datatables/Chinese.json"},
                "language": {"url": "/static/plugins/datatables/Chinese.json"}})
            $('#example2').DataTable({"language":
                    {"url": "/static/plugins/datatables/Chinese.json"},
                "language": {"url": "/static/plugins/datatables/Chinese.json"},
              "paging": true,
              "lengthChange": false,
              "searching": false,
              "ordering": true,
              "info": true,
              "autoWidth": false,
            });
            var isBorrow = [];
              {% for book in books %}
                     $("#br{{ book.BookID }}").click(function () {
                            if (isBorrow[{{ forloop.counter }}] !== true){

                                $.ajax({
                                    url : "{% url 'borrow' %}",    //提交URL
                                    type : "GET",//处理方式
                                    data : {id:{{ book.BookID }}},//提交的数据
                                    success : function (data) {
                                         if (data === "yes"){
                                            alert("借阅申请已发出");
                                            $("#br{{ book.BookID  }}").html("<button type=\"button\" class=\"btn btn-block btn-outline-danger btn-xs\">已选择</button>");
                                            isBorrow[{{ forloop.counter }}] = true;
                                         }else if (data === "out"){
                                             alert("已超出可借阅上限");
                                         }else if (data === "nobook"){
                     alert("图书在架数量为0，借阅失败");
                 }
                                    },//执行成功后的回调函
                                    error : function() {
                                        alert("借阅失败！")
                                    }

                                })
                            }
                     })
              {% endfor %}
             $(".selection").click(function () {
            var text = $(this).text()
            $("#selected").text(text)
            $("#searchtype").attr("value",text)

        })

     })
    </script>
{% endblock %}
{% block content %}
     <div class="row search-box" style="margin-top: 0px">
                <!-- 主搜索框 -->
            <form class="form-inline  m-auto" action="{% url "searchbooks" %}" method="POST">
                {% csrf_token %}
             <div class="input-group input-group-lg mb-3">
                  <div class="input-group-prepend">
                    <button type="button" id="selected" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                      {{ type }}
                    </button>
                    <ul class="dropdown-menu" style="">
                        <li class="dropdown-item"><div class="nav-link selection" >全部</div></li>
                      <li class="dropdown-item"><div class="nav-link selection" >书号</div></li>
                      <li class="dropdown-item"><div class="nav-link selection" >书名</div></li>
                      <li class="dropdown-item"><div class="nav-link selection" >作者</div></li>
                      <li class="dropdown-item"><div class="nav-link selection" >出版社</div></li>
                           <li class="dropdown-item"><div class="nav-link selection" >分类</div></li>

                    </ul>
                  </div>
                  <!-- /btn-group -->
                 <input type="text" id="searchtype" name="type" value="{{ type }}" hidden>
                  <input type="text" name="keyword" value="{{ keyword }}" class="form-control" placeholder="搜索图书">
                 <span class="input-group-append">
                    <button type="submit" class="btn gradient-color-ver" style="color: white">搜索</button>
                  </span>
                </div>

            </form>
        </div>
          <div class="row">
        <div class="col-12">

          <!-- /.card -->

          <div class="card">
            <div class="card-header">
              <h3 class="card-title">图书检索结果 </h3>
                {% if keyword %}
                  &nbsp;&nbsp;&nbsp;&nbsp;查询关键词：  {{ keyword }}
                {% endif %}
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-hover table-bordered">
                <thead>
                <tr>
                  <th>编号</th>
                  <th>书名</th>
                  <th>作者</th>
                  <th>出版社</th>
                  <th>分类</th>
                    <th>出版时间</th>
                  <th>价格</th>
                    <th>在架数量</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for book in books %}
                <tr  >
                  <td>{{ book.BookID }}</td>
                  <td><a id="book{{ book.BookID  }}" href="{% url 'bookdetail' book.BookID %}">{{ book.BName }}</a></td>
                    <td>{{ book.Author }}</td>
                    <td>{{ book.Publisher }}</td>
                    <td>{{ book.get_Category_display }}</td>
                    <td>{{ book.PubTime }}</td>
                    <td>{{ book.Price }}</td>
                     <td class="num{{ book.BookID  }}">{{ book.NumNow}}</td>
                    <td id="br{{ book.BookID  }}"><button type="button"  class="btn btn-block btn-outline-primary btn-xs">借阅</button></td>
                </tr>
                {% endfor %}
                </tbody>

              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
{% endblock %}