untitled1/urls.py
import os

from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from BuctLib import views
from django.views.generic.base import RedirectView


urlpatterns = (
    path('admin/', admin.site.urls),
    path('loginout/', views.loginout),
    path(r'', views.loginpage),
    path(r'debug/', views.hello),
    path(r'pwdmdf/', views.pwdmdf),
    path(r'admin_pwdmdf/', views.admin_pwdmdf),
    path(r'login/', views.logincheck),
    path(r'register/', views.register),
    path(r'readerindex/', views.readerindex),
    path(r'adminindex/', views.adminindex),
    path(r'registercheck/', views.registerCheck),
    path(r'book_operation/', views.book_admin),
    path(r'add_book/', views.add_book),
    path(r'check_borrow/', views.check_borrow),
    path(r'check_borrow_op/', views.check_borrow_op),
    path(r'admin_showillegal/', views.admin_showillegal),
    path(r'admin_deletebr/', views.admin_deletebr),
    path(r'remind/', views.remind_reader),
    path(r'admin_apply_check/', views.apply_check),
    path(r'apply_check_ajax/', views.apply_check_ajax),
    path(r'delete_reader/', views.delete_reader),
    path(r'delete_reader_ajax/', views.delete_reader_ajax),
    path(r'class_mdf_list/', views.class_mdf_list),
    path(r'fine_mdf_list/', views.fine_mdf_list),
    path(r'404/', views.page404),
    path(r'jump/', views.jump),
    path(r'add_user/', views.add_user),
    path(r'add_class/', views.add_class),
    path(r'add_fine/', views.add_fine),
    path(r'resetApply/', views.resetapply),
    path(r'checkpwd/', views.checkpwd),
    path(r'admin_checkpwd/', views.admin_checkpwd),
    path(r'todaycommend/', views.commend),
    path(r'admin_todaylib/', views.admin_datavisual),
    path(r'todaylib/', views.datavisual),
    path(r'getmessage/', views.getmessage),
    path(r'applyclass/', views.apllyclass),
    path(r'getborrow/', views.getborrow),
    path(r'getmesnum/', views.getmesnum),
    path(r'notreturn/', views.showbred),
    path(r'return/', views.returnbook),
    path(r'cancelNotice/', views.cancelNotice),
    path(r'admin_infmdf/', views.admin_infmdf),
    path(r'returned/', views.showreturned),
    path(r'illegal/', views.showillegal),
    path(r'sendMessage/', views.sendMessage),
    path(r'sendNotice/', views.sendNotice),
    path(r'deletebr/', views.deletebr),
    path(r'admin_class_fine_ajax/', views.admin_class_fine_ajax),
    path(r'admin_searchresult/', views.admin_searchbooks),
    url(r'class_mdf/([^/]+)/$', views.class_mdf, name='class_mdf'),
    url(r'fine_mdf/(\d+)/$', views.fine_mdf, name='fine_mdf'),
    url(r'admin_illegal_report/(\d+)/$', views.admin_illegal_report, name="admin_illegal"),
    url(r'checking/', views.checkingbooks, name='checking'),
    url(r'brrow/', views.borrow, name='borrow'),
    url(r'searchresult/', views.searchbooks, name="searchbooks"),
    url(r'delayreturn/(\d+)/$', views.delayreturn, name='delay'),
    url(r'illegalreport/(\d+)/$', views.illegal_report, name="illegal"),
    url(r'admin_allnotices', views.admin_allnotice, name='admin_allnotices'),
    url(r'admin_noticedetail/(\d+)/$', views.admin_noticedetail, name="admin_noticepage"),
    url(r'admin_bookdetail/(\d+)/$', views.admin_bookdetail, name='admin_bookdetail'),
    url(r'allnotice/', views.allnotice, name='allnotice'),
    url(r'noticedetail/(\d+)/$', views.noticedetail, name='noticepage'),
    url(r'bookdetail/(\d+)/$', views.bookdetail, name='bookdetail'),
    url(r'infomdf/', views.infmdf, name="modify information"),
    url(r'favicon.ico/', RedirectView.as_view(url=r'/static/img/icons/lib.svg')),
)

BuctLib/models.py
from django.db import models


GENDER_CHOICE = [
    ('1', '男'),
    ('2', '女'),
    ('3', '保密')
]


LibFloor = [
    ('1', '图书馆一层'),
    ('2', '图书馆二层'),
    ('3', '图书馆三层'),
    ('4', '图书馆四层'),
]

SCHOOLS = [
    ('1', '电子信息与工程学院'),
    ('2', '材料科学与工程学院'),
    ('3', '机电工程学院'),
    ('4', '化学工程学院'),
    ('5', '经济管理学院'),
    ('6', '天体物理学院'),
    ('7', '数理学院'),
    ('8', '文法学院'),
    ('9', '生命科学与技术学院'),
    ('10', '继续教育学院'),
    ('11', '马克思主义学院'),
    ('12', '国际教育学院'),
    ('13', '交通学院'),
    ('14', '中德学院'),

]

ACCOUNT_TPYE = [
    ('1', '管理员'),
    ('2', '读者'),
]

CATEGORY_CHOICE = [
        ('思政类', '思政类'),
        ('哲学类', '哲学类'),
        ('社会科学类', '社会科学类'),
        ('军事类', '军事类'),
        ('经济类', '经济类'),
        ('文化科学类', '文化科学类'),
        ('语言文字类', '语言文字类'),
        ('文学类', '文学类'),
        ('艺术类', '艺术类'),
        ('体育类', '体育类'),
        ('历史地理类', '历史地理类'),
        ('自然科学总论类', '自然科学总论类'),
        ('数理化学类', '数理化学类'),
        ('天文地球科学类', '天文地球科学类'),
        ('生物科学理类', '生物科学理类'),
        ('医药类', '医药类'),
        ('农业科学类', '农业科学类'),
        ('工业技术类', '工业技术类'),
        ('交通运输类', '交通运输类'),
        ('航空航天类', '航空航天类'),
        ('环境科学类', '环境科学类'),
        ('计算机类', '计算机类'),
        ('未分类', '未分类')
    ]


class Book(models.Model):
    """
    图书类  查询图书信息
    主键： 图书编号 BookID
    属性： ISBN ISBN 书名BName  出版社Publisher
    作者 Author 图书简介 Content 馆藏数量 NumInLib 在架数量 NumNow
    分类 Category 出版时间 PubTime
    ReadTimes 阅读数
    TODO(ChouEV) 图书封面 BImage
    """
    BookID = models.AutoField(primary_key=True, db_index=True)
    BName = models.CharField(max_length=40)
    Publisher = models.CharField(max_length=40)
    Author = models.CharField(max_length=30)
    Content = models.TextField(default="无", blank=True, null=True)
    Price = models.FloatField(default=30.0)
    NumInLib = models.PositiveSmallIntegerField(default=0)
    NumNow = models.PositiveSmallIntegerField(default=0)
    Category = models.CharField(max_length=30, default="未分类", choices=CATEGORY_CHOICE)
    PubTime = models.DateField(default="1999-10-11")
    ReadTimes = models.IntegerField(default=0)

    def __str__(self):
        return self.BName

    def save(self, *args, **kwargs):
        if self.NumInLib < self.NumNow:
            raise Exception("在架数量不能超过馆藏数量")
        else:
            super(self.__class__, self).save(*args, **kwargs)


class User(models.Model):
    """
     用户类 用于登陆
     主键： 账户名 AccountID
     属性： 密码 Password 账户类别 Type
        邮箱 Email 电话 Tel
     """
    AccountID = models.CharField(max_length=40, primary_key=True, db_index=True)
    Password = models.CharField(max_length=40)
    Type = models.CharField(choices=ACCOUNT_TPYE, default="读者", max_length=10)  # 默认为普通用户
    Email = models.EmailField(unique=True)
    Tel = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.AccountID


class Manager(models.Model):
    """
    管理员类 查询管理员信息
    主键： 工号 ManagerID
    外键： 账户名 AccountID
    属性：  性别 Gender 姓名 MName
    TODO(ChouEV) 管理员照片 MImage
    """

    ManagerID = models.CharField(primary_key=True, max_length=30, db_index=True)
    AccountID = models.OneToOneField(to="User", on_delete=models.CASCADE)
    Gender = models.CharField(max_length=10, choices=GENDER_CHOICE, default="保密")
    Name = models.CharField(max_length=30, null=True)

    def __str__(self):
        return self.ManagerID


class ReaderClass(models.Model):
    """
    读者级别类
    Class为级别
    Limited为可借阅数量
    Day为借阅天数
    """
    Class = models.CharField(max_length=10, primary_key=True, db_index=True)
    Limited = models.PositiveSmallIntegerField(default=3)
    Days = models.PositiveSmallIntegerField(default=30, null=True)

    def __str__(self):
        return self.Class


class Reader(models.Model):
    """
     读者类 查阅读者信息
     主键： 学号 ReaderID
     外键： 账户名 AccountID
     属性：  性别 Gender 姓名 SName
     学院 School
     类型 Type
    TODO(ChouEV) 读者照片 MImage
     """
    ReaderID = models.CharField(primary_key=True, max_length=30, db_index=True)
    AccountID = models.OneToOneField(User, on_delete=models.CASCADE)
    Gender = models.CharField(max_length=10, choices=GENDER_CHOICE, default="保密")
    Name = models.CharField(max_length=30, null=True, blank=True)
    School = models.CharField(max_length=30, choices=SCHOOLS, default="信息技术与科学学院")
    Class = models.ForeignKey(to="ReaderClass", on_delete=models.SET_DEFAULT, default="A")
    Type = models.CharField(max_length=10, choices=[('1', '学生'), ('2', '教职工')],  default='学生')

    def __str__(self):
        return self.ReaderID


class Fine(models.Model):
    """
    处罚规则类
    LimitDay是小于该期限的处罚金额
    FineMoney是处罚金额
    """
    LimitDay = models.PositiveSmallIntegerField(unique=True, db_index=True)
    FineMoney = models.PositiveSmallIntegerField(default=0)


class ApplyClass(models.Model):
    """
        借阅记录类
        主键 默认id
        外键 class 申请的级别 ReaderID 申请的读者ID号
    """
    Class = models.ForeignKey(to="ReaderClass", on_delete=models.CASCADE)
    ReaderID = models.ForeignKey(to="Reader", on_delete=models.CASCADE)
    Message = models.TextField(default="")


class Borrow(models.Model):
    """
    借阅记录类
    主键 学号 ReaderID &&  图书编号 BookID
    外键 学号 ReaderID &&  图书编号 BookID
    借书时间 BorrowTime 还书日期 returnTime
    续借状态 isReBorrowed
    """
    ReaderID = models.ForeignKey(to="Reader", on_delete=models.CASCADE)
    BookID = models.ForeignKey(to="Book", on_delete=models.CASCADE)
    BorrowTime = models.DateField(auto_now_add=True)
    ReturnDay = models.DateField(auto_now_add=True)
    RealreturnDay = models.DateField(default='2020-01-01')
    isReBorrowed = models.BooleanField(default=False)
    isLegal = models.NullBooleanField(default=True)
    isDelete = models.BooleanField(default=False)
    isReturned = models.BooleanField(default=False)
    isAllowed = models.NullBooleanField(null=True)

    def __str__(self):
        return "学生%s借了%s书" % (self.ReaderID, self.BookID)


class BuyIn(models.Model):
    """
    进货类
    TODO(ChouEV) 记录进货厂商 进货时间 进货书籍 进货负责人（管理员）
    """
    pass


class Message(models.Model):
    """
    消息类
    """
    STATUS = [
        ('1', '已读'),
        ('2', '未读')
    ]
    Title = models.CharField(max_length=255, verbose_name='消息标题')
    ReaderID = models.ForeignKey(to="Reader", on_delete=models.CASCADE)
    Content = models.TextField()
    MTime = models.DateTimeField(auto_now_add=True)
    Status = models.CharField(max_length=20, choices=STATUS, default="未读")

    def __str__(self):
        return "消息主题：" + self.Title


class Notice(models.Model):
    """
    公告类
    """
    Title = models.CharField(max_length=40)
    NTime = models.DateTimeField(auto_now_add=True)
    Content = models.TextField()
    ReadTimes = models.IntegerField(default=0)

    def __str__(self):
        return "公告主题：" + self.Title

templates/lib_admin/borrow/check.html
{% extends 'model/adminbase.html' %}
{% block title %}借阅审核{% endblock %}
{% block script %}
    <!-- jQuery Knob -->
<script src="/static/plugins/jquery-knob/jquery.knob.min.js"></script>

<script>
     $(function () {


           {% for rec in record %}
            $("#agree{{ rec.id }}").click(function () {
                $.ajax({
                    url: '/check_borrow_op/',
                    way: 'GET',
                    data:{id: {{ rec.id }}, way:"agree"},
                    success:function (data) {
                        if (data === "ok"){
                            $("#tr{{ rec.id }}").hide({duration:300});
                        }else{
                            alert(data)
                        }
                    },
                    error:function () {
                        alert("操作失败")
                    }

                })
            })
             $("#dis{{ rec.id }}").click(function () {
                 $.ajax({
                    url: '/check_borrow_op/',
                    way: 'GET',
                    data:{id: {{ rec.id }}, way:"disagree"},
                    success:function (data) {
                        if (data === "ok"){
                            $("#tr{{ rec.id }}").hide({duration:300});
                        }else{
                            alert("操作失败")
                        }
                    },
                    error:function () {
                        alert("操作失败")
                    }

                })
            })
         {% endfor %}
          $('.knob').knob({

      draw: function () {

        // "tron" 示例
        if (this.$.data('skin') == 'tron') {

          var a   = this.angle(this.cv)  // 角度
            ,
              sa  = this.startAngle          // 之前开始角
            ,
              sat = this.startAngle         // 开始角度
            ,
              ea                            // 之前结束角
            ,
              eat = sat + a                 // 结束角度
            ,
              r   = true

          this.g.lineWidth = this.lineWidth

          this.o.cursor
          && (sat = eat - 0.3)
          && (eat = eat + 0.3)

          if (this.o.displayPrevious) {
            ea = this.startAngle + this.angle(this.value)
            this.o.cursor
            && (sa = ea - 0.3)
            && (ea = ea + 0.3)
            this.g.beginPath()
            this.g.strokeStyle = this.previousColor
            this.g.arc(this.xy, this.xy, this.radius - this.lineWidth, sa, ea, false)
            this.g.stroke()
          }

          this.g.beginPath()
          this.g.strokeStyle = r ? this.o.fgColor : this.fgColor
          this.g.arc(this.xy, this.xy, this.radius - this.lineWidth, sat, eat, false)
          this.g.stroke()

          this.g.lineWidth = 2
          this.g.beginPath()
          this.g.strokeStyle = this.o.fgColor
          this.g.arc(this.xy, this.xy, this.radius - this.lineWidth + 1 + this.lineWidth * 2 / 3, 0, 2 * Math.PI, false)
          this.g.stroke()

          return false
        }
      }
    })
    /* 结束 JQUERY KNOB */

     })
</script>
{% endblock %}

{% block content %}

  <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">借阅申请</h3>

                <div class="card-tools">

                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0" style="height: 540px;margin-top: 20px">
                <table class="table table-hover table-head-fixed text-nowrap">
                  <thead>
                    <tr>
                      <th>编号</th>
                        <th>书号</th>
                      <th>书名</th>
                        <th>作者</th>
                      <th>读者号</th>
                      <th>姓名</th>
                      <th>类型</th>
                        <th>借阅天数</th>
                        <th>违规次数</th>
                        <th>操作</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for br,rec in borrows %}
                        <tr id="tr{{ rec.id }}">
                          <td>{{ rec.id }}</td>
                            <td>{{ rec.BookID_id }}</td>

                          <td>{{ rec.BookID.BName }}</td>
                            <td>{{ rec.BookID.Author }}</td>

                          <td>{{ rec.ReaderID.ReaderID }}</td>
                          <td>{{ rec.ReaderID.Name }}</td>
                        <td>{{ rec.ReaderID.get_Type_display }}</td>
                        <td>{{ rec.ReaderID.Class.Days }}天</td>
                          <td class="row" >
                              <div class="text-center" style="margin-left: 15px"  >
                                  {% if br.illegal > 0 %}
                                <input type="text" class="knob"  disabled="disabled" data-thickness="0.2" data-angleArc="250" data-angleOffset="-125"
                                       value="{{ br.illegal }}" data-min="0" data-max="{{ br.legal }}" data-readonly="true" data-width="40" data-height="40" data-fgColor="#f05b72">
                                  {% else %}
                                        <input type="text" class="knob"  disabled="disabled" data-thickness="0.2" data-angleArc="250" data-angleOffset="-125"
                                       value="{{ br.illegal }}" data-min="0" data-max="{{ br.legal }}" data-readonly="true" data-width="40" data-height="40" data-fgColor="#00c0ef">

                                  {% endif %}
                              </div>

                          </td>

                            <td>
                            <button id="agree{{ rec.id }}" class="btn btn-outline-primary btn-sm" >同意</button>

                                <button id="dis{{ rec.id }}" class="btn btn-outline-danger btn-sm" style="margin-left: 10px">拒绝</button>
                            </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
{% endblock %}

templates/lib_admin/borrow/illegal.html
{% extends 'model/adminbase.html' %}
{% block title %}已归还图书{% endblock %}
{% block script %}
<script>
     $(function () {
         {% for br in borrows %}
             $("#delete{{ br.id }}").click(function () {
                 $.ajax({
                     url: "/admin_deletebr/",
                     way: 'GET',
                     data: {id:{{ br.id }} },
                     success:function (data) {
                         $("#tr{{ br.id }}").hide({duration: 300})
                     },
                     error: function () {
                         alert("删除失败")
                     }
                 })
             })
              $("#remind{{ br.id }}").click(function () {
                 $.ajax({
                     url: "/remind/",
                     way: 'GET',
                     data: {id:{{ br.id }} },
                     success:function (data) {
                         alert("已发送")
                     },
                     error: function () {
                         alert("发送失败")
                     }
                 })
             })
         {% endfor %}
     })
</script>
{% endblock %}

{% block content %}
  <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">违规记录</h3>

                <div class="card-tools">

                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0" style="height: 540px;margin-top: 20px">
                <table class="table table-hover table-head-fixed text-nowrap">
                  <thead>
                    <tr>
                      <th>编号</th>
                        <th>书号</th>
                      <th>书名</th>
                      <th>作者</th>
                      <th>读者号</th>
                        <th>姓名</th>
                      <th>逾期时间</th>
                        <th>罚金</th>
                        <th>状态</th>
                        <th>操作</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for br,fine in illegal_record %}
                        <tr id="tr{{ br.id }}">
                          <td>{{ br.id }}</td>
                            <td>{{ br.BookID.BookID }}</td>
                          <td>{{ br.BookID.BName }}</td>
                          <td>{{ br.BookID.Author }}</td>
                          <td>{{ br.ReaderID_id }}</td>
                         <td>{{ br.ReaderID.Name }}</td>
                        <td>{{ fine.days }}天</td>
                        <td>{{ fine.fine_money }}元</td>

                            {% if not br.isReturned %}
                                <td ><button class="btn btn-success btn-sm" style="background-color: rgba(224,198,0,0.88);cursor: text">未归还</button></td>
                            {% else %}
                            <td ><button class="btn btn-danger btn-sm" style="background-color: #f15b6c;cursor: text">逾期归还</button></td>
                            {% endif %}
                            <td>
                                <a href="{% url 'admin_illegal' br.id %}" target="_blank"><button class="btn btn-outline-primary btn-sm" >查看处罚报告</button></a>
                                 {% if not br.isReturned %}
                               <button id="remind{{ br.id }}" class="btn btn-outline-success btn-sm" >发送提醒</button>

                                {% endif %}

                                <button id="delete{{ br.id }}" class="btn btn-outline-danger btn-sm" >删除记录</button>
                            </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
{% endblock %}

templates/lib_admin/borrow/report.html
{% extends 'model/adminbase.html' %}

{%  block title %}
    违规报告
{% endblock %}

{% block StyleSheet %}
    <style>

    </style>
{%  endblock %}
{% block script %}
    <script>
    $(function () {
        $("#fontMin").click(function () {
            $("#notice-container").css("font-size", "15px");
        })
        $("#fontMid").click(function () {
            $("#notice-container").css("font-size", "20px");
        })
        $("#fontMax").click(function () {
            $("#notice-container").css("font-size", "25px");
        })
    })
    </script>
{% endblock %}

{% block content %}
    <div class="col-lg-12 " >
            <div class="card font" >
              <div class="card-header gradient-color-her">
                <h3 class="card-title">违规报告</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="maximize"><i class="fas fa-expand" style="color: white"></i>
                  </button>
                </div>
                <!-- /.card-tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body" style="overflow-y: scroll;max-height: 100%;" >
                  <div class="row">
                    <h2 class="title m-auto font-weight-bold font-gradient" >逾期借阅处罚报告</h2>
                  </div>
                  <div class="row"  style="margin-top: 10px">
                        <p class="m-auto"><a id="fontMin" href="#">[小]</a>&nbsp;&nbsp;&nbsp;<a id="fontMid" href="#">[中]</a>&nbsp;&nbsp;&nbsp;<a id="fontMax" href="#">[大]</a></p>
                  </div>
                  <hr/>
                  <div class="noticebody row" id="notice-container" style="font-size: 20px;margin-top: 20px; min-height: 340px">


                      <div class="m-auto" >
                        <h2 style="text-align: center">读者逾期处罚单</h2>
                            <table border="1px" cellpadding="15px">
                                <tr>
                                    <th>姓名</th>
                                    <td>{{ report_br.ReaderID.Name }}</td>
                                    {% if report_br.ReaderID.Type == '1' %}
                                    <th>学号</th>
                                    {%  else %}
                                    <th>工号</th>
                                    {% endif %}
                                    <td>{{ report_br.ReaderID.ReaderID }}</td>
                                    <th>性别</th>
                                    <td>{{ report_br.ReaderID.get_Gender_display }}</td>

                                </tr>
                             <tr>
                                    <th>读者类型</th>
                                    <td>{{ report_br.ReaderID.get_Type_display }}</td>
                                    <th>学院</th>
                                    <td>{{ report_br.ReaderID.get_School_display }}</td>
                                    <th>读者等级</th>
                                    <td>{{ report_br.ReaderID.Class }}</td>

                                </tr>
                             <tr>
                                    <th>电子邮箱</th>
                                    <td colspan="2">{{ report_br.ReaderID.AccountID.Email }}</td>
                                    <th>手机号</th>
                                    <td colspan="2">{{ report_br.ReaderID.AccountID.Tel }}</td>
                                </tr>
                            <tr>
                                <th>图书编号</th>
                                <td>{{ report_br.BookID.BookID }}</td>
                                <th>借阅书名</th>
                                <td colspan="3">{{ report_br.BookID }}</td>
                            </tr>
                            <tr>
                                <th>借阅记录编号</th>
                                <td>{{ report_br.id }}</td>
                                <th>逾期时间</th>
                                <td>{{ fine.days }}天</td>
                                <th>罚金</th>
                                <td>{{ fine.fine_money }}元</td>
                            </tr>
                            <tr>
                                <th rowspan="4">处罚通知</th>
                                <td rowspan="4" colspan="5">
                                <p>
                                    亲爱的读者：<br/><br/>
                                    {% if  report_br.isLegal %}
                                    &nbsp;&nbsp;&nbsp;
                                        您在我馆借阅的图书已经逾期，根据图书馆的相关规定，我馆<br/>
                                        将会根据相应的逾期时间做出处罚。同时,系统会记录您的违规记<br/>
                                        录.鉴于您当前还没有归还图书，处罚金额会根据逾期时间有所提<br/>
                                        升，请您及时归还图书，并持此单到图书馆一楼办事处缴纳费用。<br/>
                                        如有异议和特殊情况，也可持本单到办事处咨询或申诉。<br/>

                                        <br/>
                                    {% else %}
                                        &nbsp;&nbsp;&nbsp;
                                        您借阅的图书已归还，但已经逾期，根据图书馆的相关规定，我<br/>
                                        馆将会根据响应的逾期时间做出处罚。同时,系统会记录您的违规<br/>
                                        记录.请持此单到图书馆一楼办事处缴纳费用。如有异议和特殊情<br/>
                                        况，也可持本单到办事处咨询或申诉。<br/>

                                        <br/>
                                    {% endif %}
                                        <span class="float-right">北京化工大学图书馆</span>

                                </p>
                                </td>


                            </tr>
                            </table>
                            <p class="float-right">时间:&nbsp;&nbsp;{{ nowDate }}</p>
                      <br/><br/><br/>
                      <p style="font-size: 13px" >注： 请持本单到图书馆一层缴纳处罚金，对不及时缴纳处罚金的账户，管理员将会进行注销</p>
                          </div>

                  </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>

{% endblock %}